### ISSUE TITLE
Contributing to this project

### ISSUE THREAD

**Issue by Kessir** [armcha/Ribble#6]
hi @armcha , I would love to contribute to this project as a way to improve my android skills. Is there anything I can help with?

**Comment by LilHelix** [comment]
same question

**Comment by gabrieloshiro** [comment]
There is a TODO list on the README.

**Comment by Kessir** [comment]
@gabrieloshiro I've seen the todo list but he/she could already be working on any of those tasks. We don't want to duplicate work.

One way to proceed could be to create new `issues` for the things he/she needs help with and the task can be assigned to one person.

**Comment by armcha** [comment]
Hi @Kessir , @LilHelix , thank you for interest. I don't work on any task specified in TODO list, so you can start whichever you'd like, for example, add/remove favorite would be preferable.

**Comment by Kessir** [comment]
@armcha Duly noted. I will work on the ability to add and remove favorites. I have created an issue for the task, please assign it to me.
